version: '3.8'

services:
  spring-app:
    image: spring-boot:latest
    container_name: springboot1
    ports:
      - "8080:8080"
    environment:
      - DATA_BASE_URL=jdbc:mysql://mysql-db:3306/onlineshopping
    depends_on:
      - mysql-db


  mysql-db:
    image: mysql/mysql-server:5.7
    container_name: mysql57
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onlineshopping
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "./.data/db:/var/lib/mysql"
